// Markt-Radar: Märkte, Handelszeiten und Unternehmen.
// Eintrag: [Ticker (IBKR-Suchbegriff), Name, Branche, Beschreibung, Land (nur wenn abweichend), Such-Aliase]
// Auswahl „top“: größte Unternehmen nach Börsenwert (Richtwert, Stand 2026, Reihenfolge ungefähr).
// Auswahl „growth“: kleinere, wachstumsstarke Werte. Redaktionelle Auswahl, keine Empfehlung.
window.MARKETS = [
  {
    id: "us", name: "USA", ex: "NYSE · Nasdaq", tz: "America/New_York", sess: [[570, 960]], cur: "USD", c: "US",
    top: [
      ["NVDA", "Nvidia", "Halbleiter", "Marktführer bei KI-Beschleunigern (GPUs) für Rechenzentren, dazu Gaming-Grafik und die Software-Plattform CUDA."],
      ["MSFT", "Microsoft", "Software & Cloud", "Windows, Office 365 und die Cloud Azure; enger Partner von OpenAI und führend bei Unternehmenssoftware."],
      ["AAPL", "Apple", "Hardware", "iPhone, Mac, iPad und Wearables; die wachsende Service-Sparte (App Store, iCloud, Musik) liefert hohe Margen."],
      ["AMZN", "Amazon", "E-Commerce & Cloud", "Größter Onlinehändler des Westens; die Cloud AWS liefert den Großteil des Gewinns, dazu Werbung und Prime."],
      ["GOOGL", "Alphabet", "Internet", "Google-Suche, YouTube und Android finanzieren sich über Werbung; Google Cloud, KI (Gemini) und Waymo wachsen stark."],
      ["META", "Meta Platforms", "Internet", "Facebook, Instagram und WhatsApp mit über drei Milliarden Nutzern; verdient an Werbung und investiert massiv in KI."],
      ["AVGO", "Broadcom", "Halbleiter", "Chips für Netzwerke und maßgeschneiderte KI-Chips für Hyperscaler; seit der VMware-Übernahme auch große Softwaresparte."],
      ["TSLA", "Tesla", "Auto & Energie", "Elektroautos, Batteriespeicher und Solar; setzt stark auf autonomes Fahren und Robotik (Optimus)."],
      ["BRK B", "Berkshire Hathaway", "Holding", "Mischkonzern aus Versicherungen (GEICO), Eisenbahn BNSF, Energie und großen Aktienbeteiligungen."],
      ["JPM", "JPMorgan Chase", "Bank", "Größte US-Bank: Privatkunden, Investmentbanking und Vermögensverwaltung; gilt als bestgeführte Großbank."],
      ["LLY", "Eli Lilly", "Pharma", "Abnehm- und Diabetesmittel (Mounjaro, Zepbound) treiben das Wachstum, dazu Alzheimer- und Krebsmedikamente."],
      ["V", "Visa", "Zahlungsverkehr", "Weltgrößtes Kartennetzwerk; verdient an jeder Transaktion, ohne selbst Kreditrisiko zu tragen."],
      ["ORCL", "Oracle", "Software & Cloud", "Datenbanken und Unternehmenssoftware; baut Rechenzentren für KI-Kunden wie OpenAI massiv aus."],
      ["WMT", "Walmart", "Einzelhandel", "Größter Einzelhändler der Welt; stark im Lebensmittelhandel, wachsender Onlinehandel und Werbegeschäft."],
      ["MA", "Mastercard", "Zahlungsverkehr", "Zweitgrößtes Kartennetzwerk; Gebühren pro Transaktion, dazu Datendienste und Betrugsprävention."],
      ["XOM", "ExxonMobil", "Öl & Gas", "Größter westlicher Ölkonzern: Förderung, Raffinerien und Chemie; großes Wachstumsprojekt in Guyana."],
      ["NFLX", "Netflix", "Medien", "Weltweit führender Streamingdienst mit über 300 Millionen Abos; wächst mit Werbe-Abo und Live-Inhalten."],
      ["COST", "Costco", "Einzelhandel", "Mitgliedschafts-Großmärkte; verdient vor allem an Mitgliedsgebühren, sehr treue Kundschaft."],
      ["JNJ", "Johnson & Johnson", "Pharma & Medizintechnik", "Medikamente (Krebs, Immunologie) und Medizintechnik; eines der wenigen Unternehmen mit AAA-Rating."],
      ["PLTR", "Palantir", "Software", "Datenanalyse- und KI-Plattformen für Regierungen, Militär und Unternehmen; sehr hoch bewertet."],
      ["HD", "Home Depot", "Einzelhandel", "Größte Baumarktkette der USA; abhängig von Immobilienmarkt und Renovierungen."],
      ["ABBV", "AbbVie", "Pharma", "Immunologie (Skyrizi, Rinvoq), Neurowissenschaften und Botox; ersetzt den Umsatz des früheren Blockbusters Humira."],
      ["BAC", "Bank of America", "Bank", "Zweitgrößte US-Bank mit Millionen Privatkunden, Kreditkarten und Vermögensverwaltung (Merrill)."],
      ["PG", "Procter & Gamble", "Konsumgüter", "Marken wie Pampers, Gillette, Ariel und Oral-B; stabiles, defensives Geschäft."],
      ["AMD", "AMD", "Halbleiter", "Prozessoren (Ryzen, EPYC) und KI-Beschleuniger (Instinct); wichtigster Herausforderer von Nvidia und Intel."],
      ["UNH", "UnitedHealth", "Gesundheit", "Größter US-Krankenversicherer mit Gesundheitsdiensten (Optum); zuletzt unter Druck durch steigende Behandlungskosten."],
      ["KO", "Coca-Cola", "Getränke", "Weltgrößter Getränkekonzern; liefert Sirup an Abfüller, dadurch hohe Margen und verlässliche Dividende."],
      ["GE", "GE Aerospace", "Luftfahrt", "Flugzeugtriebwerke, u. a. im CFM-Joint-Venture mit Safran; verdient vor allem an Wartung und Ersatzteilen."],
      ["CVX", "Chevron", "Öl & Gas", "Integrierter Ölkonzern mit Förderung im Perm-Becken; seit der Hess-Übernahme auch in Guyana."],
      ["CSCO", "Cisco", "Netzwerktechnik", "Router, Switches und Sicherheitssoftware für Unternehmen; profitiert vom Ausbau der Rechenzentren."],
      ["WFC", "Wells Fargo", "Bank", "Große US-Privat- und Firmenkundenbank; nach Aufhebung der Bilanzobergrenze wieder auf Wachstumskurs."],
      ["IBM", "IBM", "IT-Dienste", "Hybrid-Cloud-Software (Red Hat), Beratung und Großrechner; forscht an Quantencomputern."],
      ["TMUS", "T-Mobile US", "Telekom", "Mobilfunkanbieter mit dem größten 5G-Netz der USA; Mehrheitsaktionär ist die Deutsche Telekom."],
      ["CRM", "Salesforce", "Software", "Marktführer bei CRM-Software für Vertrieb und Kundenservice; setzt auf KI-Agenten (Agentforce)."],
      ["MS", "Morgan Stanley", "Bank", "Investmentbank mit großer Vermögensverwaltung, die stabile Gebühren liefert."],
      ["PM", "Philip Morris", "Tabak", "Marlboro außerhalb der USA; wächst mit rauchfreien Produkten wie IQOS und Zyn."],
      ["GS", "Goldman Sachs", "Bank", "Führende Investmentbank: Fusionen, Börsengänge, Handel und Vermögensverwaltung."],
      ["ABT", "Abbott", "Medizintechnik", "Diagnostik, Diabetes-Sensoren (FreeStyle Libre), Herzmedizintechnik und Ernährung."],
      ["AXP", "American Express", "Finanzdienste", "Kreditkarten mit zahlungskräftiger Kundschaft; verdient an Gebühren und Kreditzinsen."],
      ["MCD", "McDonald's", "Gastronomie", "Größte Fast-Food-Kette der Welt; verdient vor allem als Franchisegeber und Immobilienbesitzer."],
      ["LIN", "Linde", "Chemie", "Weltgrößter Industriegasehersteller; langfristige Lieferverträge sorgen für stabile Erträge."],
      ["INTU", "Intuit", "Software", "Steuer- und Buchhaltungssoftware (TurboTax, QuickBooks) sowie Credit Karma und Mailchimp."],
      ["MRK", "Merck & Co.", "Pharma", "Das Krebsmittel Keytruda ist der größte Umsatzbringer; sein Patentablauf ab 2028 ist die zentrale Herausforderung."],
      ["CAT", "Caterpillar", "Maschinenbau", "Weltgrößter Hersteller von Bau- und Bergbaumaschinen, dazu Motoren und Stromaggregate für Rechenzentren."],
      ["RTX", "RTX", "Rüstung & Luftfahrt", "Triebwerke (Pratt & Whitney), Flugzeugsysteme (Collins) und Raketenabwehr (Raytheon)."],
      ["T", "AT&T", "Telekom", "Mobilfunk und Glasfaser in den USA; konzentriert sich nach Abspaltung der Medien auf das Netzgeschäft."],
      ["UBER", "Uber", "Mobilität", "Fahrdienst- und Lieferplattform in über 70 Ländern; profitabel, mit Partnerschaften für Robotaxis."],
      ["NOW", "ServiceNow", "Software", "Cloud-Plattform zur Automatisierung von IT-Service und Arbeitsabläufen in Großunternehmen."],
      ["DIS", "Walt Disney", "Medien", "Filmstudios, Themenparks, ESPN und Disney+; die Parks liefern den Großteil des Gewinns."],
      ["PEP", "PepsiCo", "Konsumgüter", "Getränke (Pepsi, Gatorade) und Snacks (Lay's, Doritos); Snacks machen den größeren Teil aus."],
    ],
    growth: [
      ["IONQ", "IonQ", "Quantencomputing", "Baut Quantencomputer mit gefangenen Ionen und bietet sie über die Cloud an; hohe Verluste, sehr spekulativ."],
      ["OKLO", "Oklo", "Kernenergie", "Entwickelt kleine modulare Kernreaktoren für Rechenzentren und Industrie; noch ohne Umsatz, Genehmigung ausstehend."],
      ["SOUN", "SoundHound AI", "Künstliche Intelligenz", "Sprach-KI für Autos, Restaurants und Kundenservice; wächst schnell, schreibt noch Verluste."],
      ["RXRX", "Recursion", "Biotech", "Nutzt KI und automatisierte Labore zur Medikamentenentwicklung; Wirkstoffe in frühen Studien."],
      ["TMDX", "TransMedics", "Medizintechnik", "System, das Spenderorgane außerhalb des Körpers funktionsfähig hält, plus eigene Flugzeugflotte für Transporte."],
      ["HIMS", "Hims & Hers", "Gesundheit", "Online-Telemedizin im Abo für Haar-, Haut- und Gewichtsbehandlungen."],
      ["ACHR", "Archer Aviation", "Luftfahrt", "Entwickelt elektrische Senkrechtstarter (eVTOL) als Lufttaxis; Zulassung steht noch aus."],
      ["JOBY", "Joby Aviation", "Luftfahrt", "Elektrische Lufttaxis mit Toyota als Großaktionär; weit fortgeschritten im Zulassungsprozess."],
      ["LUNR", "Intuitive Machines", "Raumfahrt", "Mondlander und Weltraum-Infrastruktur, oft im Auftrag der NASA."],
      ["RKLB", "Rocket Lab", "Raumfahrt", "Kleinraketen (Electron), Satellitenkomponenten und die größere Neutron-Rakete in Entwicklung."],
      ["CELH", "Celsius", "Getränke", "Energydrinks mit Fitness-Image; Vertrieb über PepsiCo."],
      ["AEHR", "Aehr Test Systems", "Halbleiter", "Testsysteme für Siliziumkarbid-Chips und KI-Prozessoren; stark schwankende Aufträge."],
      ["SERV", "Serve Robotics", "Robotik", "Autonome Lieferroboter für Essenslieferungen in Partnerschaft mit Uber Eats."],
      ["TEM", "Tempus AI", "Gesundheit & KI", "Genomtests und KI-gestützte Datenanalyse für die Krebsbehandlung."],
      ["GRAL", "Grail", "Diagnostik", "Bluttest Galleri zur Früherkennung vieler Krebsarten; die US-Zulassung steht noch aus."],
      ["BBAI", "BigBear.ai", "Software", "KI-Analysesoftware für Verteidigung und Behörden; kleiner, verlustreicher Anbieter."],
      ["PGY", "Pagaya", "Fintech", "KI-Modelle zur Kreditvergabe für Banken und Kreditgeber."],
      ["UPST", "Upstart", "Fintech", "Online-Kreditplattform mit KI-basierter Bonitätsprüfung; stark zinsabhängig."],
      ["NVTS", "Navitas Semiconductor", "Halbleiter", "Leistungschips aus Galliumnitrid und Siliziumkarbid für Ladegeräte und KI-Rechenzentren."],
      ["RGTI", "Rigetti Computing", "Quantencomputing", "Supraleitende Quantencomputer; sehr frühes Geschäftsstadium mit hohen Verlusten."],
    ],
  },
  {
    id: "eu", name: "Europa", ex: "Xetra · Euronext · LSE · SIX", tz: "Europe/Berlin", sess: [[540, 1050]], cur: "EUR", c: "DE",
    top: [
      ["ASML", "ASML", "Halbleiterausrüstung", "Einziger Hersteller von EUV-Lithografiemaschinen, ohne die keine modernen Chips gefertigt werden können.", "NL"],
      ["SAP", "SAP", "Software", "Europas größter Softwarekonzern; der Umstieg der Kunden auf Cloud-ERP treibt das Wachstum.", "DE"],
      ["NOVO B", "Novo Nordisk", "Pharma", "Weltmarktführer bei Diabetes- und Abnehmmitteln (Ozempic, Wegovy); Wachstum zuletzt durch Konkurrenz gebremst.", "DK"],
      ["MC", "LVMH", "Luxusgüter", "Größter Luxuskonzern: Louis Vuitton, Dior, Moët Hennessy, Tiffany und Sephora; abhängig von China- und US-Nachfrage.", "FR"],
      ["NESN", "Nestlé", "Lebensmittel", "Größter Lebensmittelkonzern der Welt: Nescafé, Nespresso, KitKat, Tiernahrung; defensiv, zuletzt schwaches Wachstum.", "CH"],
      ["ROG", "Roche", "Pharma", "Pharma- und Diagnostikkonzern; führend bei Krebsmedikamenten und Labordiagnostik.", "CH"],
      ["AZN", "AstraZeneca", "Pharma", "Starke Pipeline in Onkologie, Herz-Kreislauf und seltenen Krankheiten; einer der wachstumsstärksten Pharmakonzerne Europas.", "GB"],
      ["NOVN", "Novartis", "Pharma", "Konzentriert auf innovative Medikamente (Herz, Immunologie, Krebs, Neurologie) nach Abspaltung von Sandoz.", "CH"],
      ["SHEL", "Shell", "Öl & Gas", "Integrierter Energiekonzern und weltweit größter Händler von Flüssiggas (LNG).", "GB"],
      ["HSBA", "HSBC", "Bank", "Europas größte Bank nach Bilanzsumme, mit Schwerpunkt Asien und vor allem Hongkong.", "GB"],
      ["SIE", "Siemens", "Industrie", "Automatisierung, Industriesoftware, intelligente Infrastruktur und Bahntechnik.", "DE"],
      ["OR", "L'Oréal", "Kosmetik", "Weltgrößter Kosmetikkonzern: L'Oréal Paris, Lancôme, Garnier, Kiehl's.", "FR"],
      ["RMS", "Hermès", "Luxusgüter", "Birkin-Taschen, Seidenschals und Leder; extrem hohe Margen und Preismacht, familienkontrolliert.", "FR"],
      ["TTE", "TotalEnergies", "Energie", "Öl, Gas und LNG sowie ein wachsender Strom- und Erneuerbaren-Bereich.", "FR"],
      ["ALV", "Allianz", "Versicherung", "Einer der größten Versicherer der Welt; Sach- und Lebensversicherung sowie Vermögensverwaltung (PIMCO).", "DE"],
      ["SAN", "Banco Santander", "Bank", "Großbank mit Kernmärkten Spanien, Großbritannien, Brasilien, Mexiko und USA.", "ES"],
      ["SAN", "Sanofi", "Pharma", "Pharmakonzern mit dem Blockbuster Dupixent (Immunologie) und einem großen Impfstoffgeschäft.", "FR"],
      ["AIR", "Airbus", "Luftfahrt", "Weltgrößter Flugzeugbauer nach Auslieferungen; volle Auftragsbücher, Engpass sind die Lieferketten.", "FR"],
      ["SU", "Schneider Electric", "Elektrotechnik", "Stromverteilung sowie Gebäude- und Industrieautomatisierung; profitiert vom Rechenzentrums-Boom.", "FR"],
      ["DTE", "Deutsche Telekom", "Telekom", "Größter europäischer Telekomkonzern; die Mehrheit an T-Mobile US liefert den Großteil des Gewinns.", "DE"],
      ["ULVR", "Unilever", "Konsumgüter", "Dove, Knorr, Rexona; hat das Eiscreme-Geschäft abgespalten und fokussiert auf Pflege- und Lebensmittelmarken.", "GB"],
      ["UBSG", "UBS", "Bank", "Größter Vermögensverwalter der Welt; integriert die übernommene Credit Suisse.", "CH"],
      ["IBE", "Iberdrola", "Versorger", "Einer der größten Stromkonzerne der Welt: Netze und Erneuerbare in Spanien, Großbritannien, USA und Brasilien.", "ES"],
      ["RACE", "Ferrari", "Auto", "Luxus-Sportwagen mit knapper Stückzahl und sehr hohen Margen, dazu die Formel 1.", "IT"],
      ["ITX", "Inditex", "Mode", "Zara, Massimo Dutti und Pull&Bear; schnelle Lieferkette und hohe Profitabilität.", "ES"],
      ["BNP", "BNP Paribas", "Bank", "Größte Bank der Eurozone: Privatkunden, Firmenkunden und Investmentbanking.", "FR"],
      ["ABBN", "ABB", "Elektrotechnik", "Elektrifizierung, Robotik und Automatisierung; wächst durch Netzausbau und Rechenzentren.", "CH"],
      ["CFR", "Richemont", "Luxusgüter", "Schmuck und Uhren: Cartier, Van Cleef & Arpels, IWC, Jaeger-LeCoultre.", "CH"],
      ["RHM", "Rheinmetall", "Rüstung", "Größter deutscher Rüstungskonzern: Munition, Panzer, Flugabwehr; profitiert von steigenden Verteidigungsbudgets.", "DE"],
      ["UCG", "UniCredit", "Bank", "Italienische Großbank mit starker Präsenz in Deutschland (HypoVereinsbank) und Osteuropa.", "IT"],
      ["ISP", "Intesa Sanpaolo", "Bank", "Größte Bank Italiens: Privatkunden, Vermögensverwaltung und Versicherungen.", "IT"],
      ["ENEL", "Enel", "Versorger", "Italiens größter Energiekonzern mit Netzen und Erneuerbaren in Europa und Lateinamerika.", "IT"],
      ["BBVA", "BBVA", "Bank", "Spanische Großbank mit sehr profitablem Mexiko-Geschäft und einer Tochter in der Türkei.", "ES"],
      ["SAF", "Safran", "Luftfahrt", "Flugzeugtriebwerke (CFM mit GE), Fahrwerke und Kabinenausstattung.", "FR"],
      ["EL", "EssilorLuxottica", "Brillen", "Weltmarktführer für Brillengläser und Fassungen (Ray-Ban, Oakley), dazu smarte Brillen mit Meta.", "FR"],
      ["AI", "Air Liquide", "Chemie", "Industrie- und Medizingase mit stabilen Langfristverträgen.", "FR"],
      ["MUV2", "Munich Re", "Rückversicherung", "Weltgrößter Rückversicherer; trägt Großrisiken anderer Versicherer, dazu der Erstversicherer ERGO.", "DE"],
      ["ZURN", "Zurich Insurance", "Versicherung", "Globaler Sach- und Lebensversicherer mit starkem US-Geschäft (Farmers).", "CH"],
      ["RIO", "Rio Tinto", "Bergbau", "Zweitgrößter Bergbaukonzern der Welt: Eisenerz, Aluminium, Kupfer und Lithium.", "GB"],
      ["GSK", "GSK", "Pharma", "Impfstoffe, HIV-Medikamente (ViiV) und Spezialmedizin.", "GB"],
      ["REL", "RELX", "Information", "Fachinformation und Analysen für Recht, Wissenschaft (Elsevier) und Risikoprüfung; zunehmend KI-gestützt.", "GB"],
      ["LSEG", "London Stock Exchange Group", "Finanzdaten", "Börse London und großer Finanzdatenanbieter (ehemals Refinitiv), Partnerschaft mit Microsoft.", "GB"],
      ["BATS", "British American Tobacco", "Tabak", "Lucky Strike, Dunhill, Vuse und Velo; hohe Dividende bei schrumpfendem Zigarettenmarkt.", "GB"],
      ["BARC", "Barclays", "Bank", "Britische Universalbank mit großem Investmentbanking.", "GB"],
      ["ADYEN", "Adyen", "Zahlungsverkehr", "Zahlungsplattform für Großkunden wie Uber, Spotify und eBay; hochprofitabel und schnell wachsend.", "NL"],
      ["PRX", "Prosus", "Internet", "Beteiligungsholding mit großem Tencent-Anteil, dazu Lieferdienste und Kleinanzeigen.", "NL"],
      ["INGA", "ING", "Bank", "Niederländische Großbank mit starkem Direktbankgeschäft, auch in Deutschland.", "NL"],
      ["ATCO A", "Atlas Copco", "Maschinenbau", "Kompressoren, Vakuumtechnik (u. a. für Chipfabriken) und Industriewerkzeuge.", "SE"],
      ["INVE B", "Investor AB", "Holding", "Beteiligungsgesellschaft der Familie Wallenberg an ABB, Atlas Copco, AstraZeneca und weiteren.", "SE"],
      ["DSV", "DSV", "Logistik", "Einer der größten Speditions- und Logistikkonzerne der Welt; mit der Übernahme von DB Schenker noch größer.", "DK"],
    ],
    growth: [
      ["HAG", "Hensoldt", "Rüstungselektronik", "Radar- und Sensortechnik für Verteidigung, u. a. für Luftabwehrsysteme wie IRIS-T.", "DE"],
      ["R3NK", "Renk", "Antriebstechnik", "Getriebe für Panzer, Schiffe und Industrie; Marktführer bei Panzergetrieben.", "DE"],
      ["NDX1", "Nordex", "Windenergie", "Hersteller von Windturbinen an Land; nach Verlustjahren zurück in der Gewinnzone.", "DE"],
      ["AG1", "Auto1 Group", "Online-Handel", "Europas größte Online-Plattform für Gebrauchtwagen (Autohero, wirkaufendeinauto.de).", "DE"],
      ["IOS", "IONOS", "Cloud", "Webhosting, Domains und Cloud-Dienste für kleine Firmen; Tochter von United Internet.", "DE"],
      ["VH2", "Friedrich Vorwerk", "Energieinfrastruktur", "Baut Gas-, Wasserstoff- und Stromleitungen; profitiert von der Energiewende.", "DE"],
      ["EUZ", "Eckert & Ziegler", "Medizintechnik", "Radioaktive Isotope für Krebsdiagnostik und -therapie (Radiopharmazie).", "DE"],
      ["CAMX", "Camurus", "Pharma", "Depot-Technologie für lang wirkende Medikamente, u. a. gegen Opioidabhängigkeit.", "SE"],
      ["SECT B", "Sectra", "Medizin-IT", "Software für medizinische Bildgebung und Cybersicherheit.", "SE"],
      ["TRUE B", "Truecaller", "App", "Anrufer-Erkennung und Spam-Schutz, besonders stark in Indien.", "SE"],
      ["BFIT", "Basic-Fit", "Fitness", "Größte Fitnessstudio-Kette Europas im Discount-Segment.", "NL"],
      ["PHARM", "Pharming", "Biotech", "Medikamente gegen seltene Erkrankungen (Ruconest, Joenja).", "NL"],
      ["EXENS", "Exosens", "Photonik", "Detektoren und Bildverstärker für Nachtsicht, Forschung und Industrie.", "FR"],
      ["GAW", "Games Workshop", "Unterhaltung", "Warhammer-Figuren und Lizenzen; sehr profitabel.", "GB"],
      ["ONT", "Oxford Nanopore", "Biotech", "DNA-Sequenzierung per Nanoporen-Technologie; wachsender Umsatz, noch Verluste.", "GB"],
      ["TRST", "Trustpilot", "Internet", "Plattform für Online-Bewertungen von Unternehmen; inzwischen profitabel.", "GB"],
      ["BAVA", "Bavarian Nordic", "Biotech", "Impfstoffe gegen Mpox, Tollwut und Chikungunya.", "DK"],
      ["KIT", "Kitron", "Elektronikfertigung", "Auftragsfertiger für Elektronik in Rüstung, Medizin und Industrie.", "NO"],
      ["COTN", "Comet", "Technologie", "Hochfrequenz- und Röntgentechnik für Chipfertigung und Inspektion.", "CH"],
      ["AERO", "Montana Aerospace", "Luftfahrt", "Leichtbau-Komponenten aus Aluminium und Titan für Airbus und Boeing.", "CH"],
    ],
  },
  {
    id: "jp", name: "Japan", ex: "Tokyo Stock Exchange", tz: "Asia/Tokyo", sess: [[540, 690], [750, 930]], cur: "JPY", c: "JP",
    top: [
      ["7203", "Toyota Motor", "Auto", "Weltgrößter Autobauer nach Absatz; führend bei Hybridantrieben, dazu eine große Finanzsparte."],
      ["8306", "Mitsubishi UFJ", "Bank", "Größte Bankengruppe Japans; profitiert vom Ende der Nullzinspolitik, beteiligt an Morgan Stanley."],
      ["6758", "Sony Group", "Unterhaltung & Elektronik", "PlayStation, Musik, Filme und Bildsensoren; wandelt sich zum Unterhaltungskonzern."],
      ["6501", "Hitachi", "Industrie & IT", "Stromnetze, Bahntechnik und IT-Dienste; gilt als gelungenes Beispiel für Konzernumbau."],
      ["9984", "SoftBank Group", "Beteiligungen", "Technologie-Investor; Hauptwerte sind Arm und Beteiligungen an OpenAI, sehr schwankungsreich."],
      ["9983", "Fast Retailing", "Mode", "Mutterkonzern von Uniqlo; Marktführer bei Basic-Mode in Asien mit schnellem Auslandswachstum."],
      ["8316", "Sumitomo Mitsui FG", "Bank", "Zweitgrößte Bankengruppe Japans mit Wachstum in Indien und Südostasien."],
      ["6098", "Recruit Holdings", "Internet & Personal", "Jobportale Indeed und Glassdoor sowie Personaldienste."],
      ["6861", "Keyence", "Automatisierung", "Sensoren und Messtechnik für Fabriken; extrem hohe Margen durch Direktvertrieb."],
      ["8035", "Tokyo Electron", "Halbleiterausrüstung", "Anlagen für die Chipfertigung (Beschichtung, Ätzen); weltweit Nummer drei der Branche."],
      ["7974", "Nintendo", "Videospiele", "Switch-Konsolen und Marken wie Mario und Zelda, beteiligt an Pokémon."],
      ["8058", "Mitsubishi Corp", "Handelshaus", "Größtes Handelshaus Japans: Rohstoffe, Energie, Lebensmittel; Warren Buffett ist Aktionär."],
      ["8411", "Mizuho FG", "Bank", "Dritte große Bankengruppe Japans mit Fokus auf Firmenkunden und Investmentbanking."],
      ["8766", "Tokio Marine", "Versicherung", "Größter Sachversicherer Japans mit großem US-Geschäft."],
      ["7011", "Mitsubishi Heavy Industries", "Industrie & Rüstung", "Gasturbinen, Rüstung und Raumfahrt; profitiert von Japans Aufrüstung und steigendem Strombedarf."],
      ["8001", "ITOCHU", "Handelshaus", "Handelshaus mit Fokus auf Konsum, Textil und Lebensmittel (FamilyMart)."],
      ["4063", "Shin-Etsu Chemical", "Chemie", "Weltmarktführer bei Siliziumwafern und PVC."],
      ["9433", "KDDI", "Telekom", "Zweitgrößter Mobilfunkanbieter Japans (Marke au)."],
      ["4519", "Chugai Pharmaceutical", "Pharma", "Mehrheitlich im Besitz von Roche; starke Eigenentwicklungen, u. a. die Abnehmpille Orforglipron für Lilly."],
      ["9432", "NTT", "Telekom", "Größter Telekomkonzern Japans: Festnetz, Mobilfunk (Docomo) und IT-Dienste."],
      ["8031", "Mitsui & Co", "Handelshaus", "Handelshaus mit Schwerpunkt Eisenerz, LNG und Infrastruktur."],
      ["9434", "SoftBank Corp", "Telekom", "Mobilfunktochter der SoftBank Group, dazu LINE Yahoo und der Bezahldienst PayPay."],
      ["6857", "Advantest", "Halbleiter-Testsysteme", "Weltmarktführer bei Testsystemen für Chips, u. a. für KI-Prozessoren."],
      ["4568", "Daiichi Sankyo", "Pharma", "Führend bei Antikörper-Wirkstoff-Konjugaten gegen Krebs (Enhertu mit AstraZeneca)."],
      ["4502", "Takeda", "Pharma", "Größter Pharmakonzern Japans mit starkem US-Geschäft; hohe Schulden seit der Shire-Übernahme."],
      ["7267", "Honda Motor", "Auto & Motorräder", "Weltgrößter Motorradhersteller, dazu Autos, Motoren und Flugzeuge (HondaJet)."],
      ["7741", "Hoya", "Optik & Halbleiter", "Brillengläser, medizinische Endoskope und Maskenrohlinge für die Chipfertigung."],
      ["3382", "Seven & i", "Einzelhandel", "Betreiber von 7-Eleven weltweit; stand im Fokus eines Übernahmeangebots von Couche-Tard."],
      ["4661", "Oriental Land", "Freizeit", "Betreiber von Tokyo Disneyland und Tokyo DisneySea."],
      ["6702", "Fujitsu", "IT-Dienste", "Größter IT-Dienstleister Japans: Software, Beratung und Supercomputer."],
      ["6902", "Denso", "Autozulieferer", "Einer der größten Autozulieferer der Welt, Teil der Toyota-Gruppe."],
      ["2914", "Japan Tobacco", "Tabak", "Drittgrößter Tabakkonzern der Welt (Winston, Camel außerhalb der USA); hohe Dividende."],
      ["6981", "Murata Manufacturing", "Elektronikbauteile", "Weltmarktführer bei Keramik-Kondensatoren für Smartphones, Autos und Server."],
      ["8801", "Mitsui Fudosan", "Immobilien", "Größter Immobilienkonzern Japans: Büros, Einkaufszentren, Wohnungen."],
      ["5401", "Nippon Steel", "Stahl", "Größter Stahlhersteller Japans; hat 2025 U.S. Steel übernommen."],
      ["7751", "Canon", "Elektronik", "Kameras, Drucker, Medizintechnik und Lithografieanlagen."],
      ["6367", "Daikin Industries", "Klimatechnik", "Weltgrößter Hersteller von Klimaanlagen und Wärmepumpen."],
      ["6301", "Komatsu", "Maschinenbau", "Zweitgrößter Baumaschinenhersteller der Welt nach Caterpillar."],
      ["8002", "Marubeni", "Handelshaus", "Handelshaus mit Agrarrohstoffen, Energie und Infrastruktur."],
      ["8053", "Sumitomo Corp", "Handelshaus", "Handelshaus mit Metallen, Medien, Immobilien und Infrastruktur."],
      ["6954", "FANUC", "Automatisierung", "Weltmarktführer bei CNC-Steuerungen und Industrierobotern."],
      ["6701", "NEC", "IT", "IT-Dienste, Netzwerktechnik, Gesichtserkennung und Verteidigungselektronik."],
      ["4543", "Terumo", "Medizintechnik", "Katheter, Infusionssysteme und Blutmanagement."],
      ["6503", "Mitsubishi Electric", "Elektrotechnik", "Fabrikautomatisierung, Klimatechnik, Leistungshalbleiter und Rüstung."],
      ["5108", "Bridgestone", "Reifen", "Einer der größten Reifenhersteller der Welt."],
      ["8750", "Dai-ichi Life", "Versicherung", "Großer Lebensversicherer mit Auslandsgeschäft in den USA und Australien."],
      ["8591", "ORIX", "Finanzdienste", "Leasing, Versicherungen, Immobilien und Beteiligungen."],
      ["6146", "Disco", "Halbleiterausrüstung", "Weltmarktführer bei Säge- und Schleifmaschinen für Chips; wichtig für KI-Speicher (HBM)."],
      ["8604", "Nomura Holdings", "Finanzen", "Größte Investmentbank und größter Broker Japans."],
      ["7269", "Suzuki Motor", "Auto", "Kleinwagen und Motorräder; über Maruti Suzuki Marktführer in Indien."],
    ],
    growth: [
      ["4443", "Sansan", "Software", "Cloud-Software für Visitenkarten, Kontaktdaten und Rechnungen (Bill One)."],
      ["4478", "freee", "Software", "Cloud-Buchhaltung und Personalsoftware für kleine Firmen."],
      ["3994", "Money Forward", "Fintech", "Finanz-Apps für Privatleute und Cloud-Buchhaltung für Unternehmen."],
      ["4483", "JMDC", "Gesundheitsdaten", "Anonymisierte Krankenversicherungsdaten für die Pharmaforschung; mehrheitlich im Besitz von Omron."],
      ["4194", "Visional", "Personal", "Jobplattform BizReach für Fachkräfte und HR-Software."],
      ["3923", "Rakus", "Software", "Cloud-Software für Spesen, Rechnungen und E-Mail-Verwaltung."],
      ["3697", "SHIFT", "IT-Dienste", "Software-Tests und Qualitätssicherung; wächst schnell, auch durch Übernahmen."],
      ["4180", "Appier", "KI & Marketing", "KI-Software für Werbung und Kundenansprache, stark in Asien."],
      ["4477", "BASE", "E-Commerce", "Plattform für eigene Online-Shops und der Zahlungsdienst PAY.JP."],
      ["3778", "Sakura Internet", "Cloud", "Rechenzentren und GPU-Cloud für KI; staatlich zertifizierter Cloud-Anbieter."],
      ["6526", "Socionext", "Halbleiter", "Entwirft Spezialchips (SoC) für Autos, Rechenzentren und Kameras."],
      ["4385", "Mercari", "E-Commerce", "Größte Second-Hand-App Japans, dazu der Zahlungsdienst Merpay."],
      ["4480", "Medley", "Gesundheit & Personal", "Jobportal für Pflegekräfte und Software für Arztpraxen."],
      ["5253", "Cover", "Unterhaltung", "Agentur für virtuelle YouTuber (hololive) mit Merchandising."],
      ["5032", "ANYCOLOR", "Unterhaltung", "VTuber-Agentur NIJISANJI; hohe Margen durch Merchandise."],
      ["6544", "Japan Elevator Service", "Dienstleistung", "Unabhängige Aufzugwartung, günstiger als der Herstellerservice."],
      ["2492", "Infomart", "Software", "B2B-Plattform für Bestellungen und Rechnungen in der Gastronomie."],
      ["3993", "PKSHA Technology", "Künstliche Intelligenz", "KI-Software für Kundenservice und Automatisierung."],
      ["4475", "HENNGE", "IT-Sicherheit", "Cloud-Sicherheit und Single Sign-on für Unternehmen."],
      ["9348", "ispace", "Raumfahrt", "Mondlander-Missionen; sehr spekulativ nach zwei gescheiterten Landungen."],
    ],
  },
  {
    id: "kr", name: "Korea", ex: "Korea Exchange (KOSPI · KOSDAQ)", tz: "Asia/Seoul", sess: [[540, 930]], cur: "KRW", c: "KR",
    top: [
      ["005930", "Samsung Electronics", "Halbleiter & Elektronik", "Größter Speicherchip-Hersteller der Welt, dazu Smartphones und Fernseher."],
      ["000660", "SK Hynix", "Halbleiter", "Zweitgrößter Speicherhersteller; Marktführer bei HBM-Speicher für KI-Chips von Nvidia."],
      ["373220", "LG Energy Solution", "Batterien", "Einer der größten Hersteller von Batterien für Elektroautos."],
      ["207940", "Samsung Biologics", "Biotech", "Einer der größten Auftragsfertiger für Biopharmazeutika weltweit."],
      ["005380", "Hyundai Motor", "Auto", "Größter Autobauer Koreas; zusammen mit Kia weltweit die Nummer drei."],
      ["000270", "Kia", "Auto", "Autohersteller der Hyundai-Gruppe, stark bei SUVs und Elektroautos."],
      ["068270", "Celltrion", "Biotech", "Biosimilars (Nachahmer biologischer Medikamente) und eigene Antikörper."],
      ["105560", "KB Financial", "Bank", "Größte Finanzgruppe Koreas."],
      ["055550", "Shinhan Financial", "Bank", "Zweitgrößte Finanzgruppe Koreas mit Auslandsgeschäft in Vietnam und Japan."],
      ["012450", "Hanwha Aerospace", "Rüstung", "Panzerhaubitzen K9, Raketenwerfer und Flugzeugtriebwerke; starkes Exportwachstum."],
      ["035420", "NAVER", "Internet", "Größte Suchmaschine Koreas, dazu Webtoons, E-Commerce und Zahlungen."],
      ["005490", "POSCO Holdings", "Stahl", "Größter Stahlhersteller Koreas mit einer Sparte für Batteriematerial."],
      ["329180", "HD Hyundai Heavy Industries", "Schiffbau", "Weltgrößter Schiffbauer: LNG-Tanker und Marineschiffe."],
      ["028260", "Samsung C&T", "Bau & Holding", "Bau, Handel und Mode; zentrale Holding der Samsung-Gruppe."],
      ["012330", "Hyundai Mobis", "Autozulieferer", "Teile und Module für Hyundai und Kia."],
      ["086790", "Hana Financial", "Bank", "Große koreanische Finanzgruppe."],
      ["032830", "Samsung Life", "Versicherung", "Größter Lebensversicherer Koreas; hält ein großes Paket Samsung-Electronics-Aktien."],
      ["035720", "Kakao", "Internet", "Messenger KakaoTalk, Bezahldienste, Mobilität und Unterhaltung."],
      ["006400", "Samsung SDI", "Batterien", "Batterien für Elektroautos und Energiespeicher."],
      ["051910", "LG Chem", "Chemie", "Petrochemie und Batteriematerialien; Mehrheitsaktionär von LG Energy Solution."],
      ["015760", "KEPCO", "Versorger", "Staatlicher Stromkonzern Koreas; baut Kernkraftwerke auch im Ausland."],
      ["034020", "Doosan Enerbility", "Energietechnik", "Komponenten für Kernkraftwerke, Gasturbinen und kleine Reaktoren (SMR)."],
      ["042660", "Hanwha Ocean", "Schiffbau", "Früher Daewoo Shipbuilding; LNG-Tanker und U-Boote."],
      ["010130", "Korea Zinc", "Metalle", "Weltgrößter Zinkschmelzer, dazu Blei, Silber und Kupfer."],
      ["009540", "HD Korea Shipbuilding & Offshore", "Schiffbau", "Zwischenholding der HD-Hyundai-Werften."],
      ["011200", "HMM", "Reederei", "Größte Containerreederei Koreas."],
      ["138040", "Meritz Financial", "Finanzen", "Versicherungen und Wertpapierhandel mit hoher Kapitalrendite."],
      ["000810", "Samsung Fire & Marine", "Versicherung", "Größter Sachversicherer Koreas."],
      ["033780", "KT&G", "Tabak & Ginseng", "Tabakmarktführer Koreas und Ginseng-Produkte (Korea Ginseng Corp)."],
      ["003550", "LG Corp", "Holding", "Holding der LG-Gruppe."],
      ["066570", "LG Electronics", "Elektronik", "Haushaltsgeräte, Fernseher und Autokomponenten."],
      ["259960", "Krafton", "Videospiele", "Entwickler von PUBG: Battlegrounds."],
      ["010140", "Samsung Heavy Industries", "Schiffbau", "Werft für LNG-Tanker und schwimmende Gasanlagen."],
      ["017670", "SK Telecom", "Telekom", "Größter Mobilfunkanbieter Koreas."],
      ["030200", "KT", "Telekom", "Festnetz, Mobilfunk und Cloud in Korea."],
      ["034730", "SK Inc", "Holding", "Holding der SK-Gruppe (SK Hynix, SK Innovation)."],
      ["096770", "SK Innovation", "Energie & Batterien", "Raffinerien, Chemie und Batterien (SK On)."],
      ["316140", "Woori Financial", "Bank", "Große koreanische Bankengruppe."],
      ["018260", "Samsung SDS", "IT-Dienste", "IT- und Logistikdienste der Samsung-Gruppe."],
      ["064350", "Hyundai Rotem", "Rüstung & Bahn", "Kampfpanzer K2 und Hochgeschwindigkeitszüge."],
      ["267260", "HD Hyundai Electric", "Elektrotechnik", "Transformatoren und Schaltanlagen; profitiert vom Netzausbau in den USA."],
      ["402340", "SK Square", "Beteiligungen", "Investmentholding mit großem Anteil an SK Hynix."],
      ["024110", "Industrial Bank of Korea", "Bank", "Staatliche Bank für kleine und mittlere Unternehmen."],
      ["009150", "Samsung Electro-Mechanics", "Elektronikbauteile", "Kondensatoren, Kameramodule und Chip-Substrate."],
      ["047810", "Korea Aerospace Industries", "Luftfahrt", "Kampfjet KF-21, Trainingsflugzeuge und Hubschrauber."],
      ["003670", "POSCO Future M", "Batteriematerialien", "Kathoden- und Anodenmaterial für Batterien."],
      ["323410", "KakaoBank", "Bank", "Größte reine Onlinebank Koreas."],
      ["352820", "HYBE", "Unterhaltung", "Musiklabel von BTS und weiteren K-Pop-Gruppen."],
      ["010950", "S-Oil", "Raffinerie", "Raffineriekonzern, Mehrheitsaktionär ist Saudi Aramco."],
      ["086280", "Hyundai Glovis", "Logistik", "Logistik und Autotransportschiffe der Hyundai-Gruppe."],
    ],
    growth: [
      ["196170", "Alteogen", "Biotech", "Technologie, die Infusionsmedikamente als Spritze unter die Haut verabreichbar macht (Lizenz an MSD)."],
      ["028300", "HLB", "Biotech", "Entwickelt das Krebsmittel Rivoceranib; die US-Zulassung wurde mehrfach verschoben."],
      ["247540", "EcoPro BM", "Batteriematerialien", "Hersteller von nickelreichem Kathodenmaterial."],
      ["141080", "LigaChem Biosciences", "Biotech", "Plattform für Antikörper-Wirkstoff-Konjugate (ADC) mit Lizenzen an große Pharmafirmen."],
      ["145020", "Hugel", "Medizin-Ästhetik", "Botulinumtoxin (Letybo) und Hautfüller."],
      ["214150", "Classys", "Medizintechnik", "Ästhetische Geräte zur Hautstraffung per Ultraschall."],
      ["058470", "Leeno Industrial", "Halbleiter-Test", "Testsockel und Prüfspitzen für Chips."],
      ["277810", "Rainbow Robotics", "Robotik", "Humanoide und kollaborative Roboter; Samsung ist größter Aktionär."],
      ["240810", "Wonik IPS", "Halbleiterausrüstung", "Abscheideanlagen für die Chipfertigung."],
      ["036930", "Jusung Engineering", "Halbleiterausrüstung", "Beschichtungsanlagen für Chips, Displays und Solarzellen."],
      ["039030", "EO Technics", "Laseranlagen", "Laser-Markier- und Schneideanlagen für Halbleiter."],
      ["357780", "Soulbrain", "Chemie", "Spezialchemikalien für Chips und Batterien."],
      ["108490", "Robotis", "Robotik", "Servomotoren (Dynamixel) und Roboterbausätze."],
      ["042700", "Hanmi Semiconductor", "Halbleiterausrüstung", "TC-Bonder für HBM-Speicher, Hauptkunde ist SK Hynix."],
      ["298380", "ABL Bio", "Biotech", "Bispezifische Antikörper und Technologie zur Überwindung der Blut-Hirn-Schranke."],
      ["263750", "Pearl Abyss", "Videospiele", "Black Desert und das neue Crimson Desert."],
      ["112040", "Wemade", "Videospiele", "Legend of Mir und Blockchain-Spiele (WEMIX)."],
      ["067310", "Hana Micron", "Halbleiter", "Chip-Verpackung und -Test, auch in Vietnam und Brasilien."],
      ["222800", "Simmtech", "Leiterplatten", "Substrate für Speichermodule."],
      ["348370", "Enchem", "Batteriematerialien", "Elektrolyte für Lithium-Ionen-Batterien."],
    ],
  },
  {
    id: "au", name: "Australien", ex: "ASX", tz: "Australia/Sydney", sess: [[600, 960]], cur: "AUD", c: "AU",
    top: [
      ["BHP", "BHP Group", "Bergbau", "Größter Bergbaukonzern der Welt: Eisenerz, Kupfer und Kali."],
      ["CBA", "Commonwealth Bank", "Bank", "Größte Bank Australiens; im internationalen Vergleich sehr hoch bewertet."],
      ["CSL", "CSL", "Biotech", "Blutplasma-Therapien, Impfstoffe (Seqirus) und Nierenmedikamente (Vifor)."],
      ["NAB", "National Australia Bank", "Bank", "Große Bank mit Stärke bei Geschäftskunden."],
      ["WBC", "Westpac", "Bank", "Älteste Bank Australiens."],
      ["ANZ", "ANZ Group", "Bank", "Große Bank für Australien und Neuseeland."],
      ["WES", "Wesfarmers", "Mischkonzern", "Baumarktkette Bunnings, Kmart, Chemie und Lithium."],
      ["MQG", "Macquarie Group", "Finanzen", "Investmentbank und weltweit größter Infrastruktur-Vermögensverwalter."],
      ["GMG", "Goodman Group", "Immobilien", "Logistikimmobilien und Rechenzentren weltweit."],
      ["FMG", "Fortescue", "Bergbau", "Eisenerzförderer mit Ambitionen bei grünem Wasserstoff."],
      ["RIO", "Rio Tinto", "Bergbau", "Eisenerz, Aluminium und Kupfer (Australien-Notierung)."],
      ["TLS", "Telstra", "Telekom", "Größter Telekomanbieter Australiens."],
      ["WDS", "Woodside Energy", "Energie", "Größter Öl- und Gasproduzent Australiens, stark bei LNG."],
      ["WOW", "Woolworths", "Einzelhandel", "Größte Supermarktkette Australiens."],
      ["TCL", "Transurban", "Infrastruktur", "Betreiber von Mautstraßen in Australien und Nordamerika."],
      ["ALL", "Aristocrat Leisure", "Glücksspiel", "Spielautomaten und Mobile Games."],
      ["RMD", "ResMed", "Medizintechnik", "Geräte gegen Schlafapnoe (CPAP)."],
      ["XRO", "Xero", "Software", "Cloud-Buchhaltung für kleine Unternehmen weltweit."],
      ["WTC", "WiseTech Global", "Software", "Logistiksoftware CargoWise; Debatten um die Unternehmensführung."],
      ["QBE", "QBE Insurance", "Versicherung", "Internationaler Sachversicherer."],
      ["COL", "Coles Group", "Einzelhandel", "Zweitgrößte Supermarktkette Australiens."],
      ["SUN", "Suncorp", "Versicherung", "Sachversicherer in Australien und Neuseeland."],
      ["REA", "REA Group", "Internet", "Führendes Immobilienportal realestate.com.au."],
      ["PME", "Pro Medicus", "Medizin-IT", "Software für medizinische Bildgebung; extrem hohe Margen und Bewertung."],
      ["NST", "Northern Star", "Bergbau", "Einer der größten Goldproduzenten Australiens."],
      ["S32", "South32", "Bergbau", "Aluminium, Mangan, Kupfer und Zink."],
      ["BXB", "Brambles", "Logistik", "Palettenvermietung (CHEP) weltweit."],
      ["CPU", "Computershare", "Finanzdienste", "Aktienregister und Treuhanddienste."],
      ["ORG", "Origin Energy", "Energie", "Strom- und Gasversorger mit Anteil am britischen Anbieter Octopus Energy."],
      ["STO", "Santos", "Energie", "Öl- und Gasförderer mit LNG-Projekten."],
      ["SCG", "Scentre Group", "Immobilien", "Westfield-Einkaufszentren in Australien und Neuseeland."],
      ["EVN", "Evolution Mining", "Bergbau", "Gold- und Kupferproduzent."],
      ["SHL", "Sonic Healthcare", "Gesundheit", "Labordiagnostik in Australien, Europa und den USA."],
      ["QAN", "Qantas", "Luftfahrt", "Größte Fluggesellschaft Australiens."],
      ["IAG", "Insurance Australia Group", "Versicherung", "Größter Sachversicherer Australiens."],
      ["ASX", "ASX Ltd", "Börse", "Betreiber der australischen Börse."],
      ["CAR", "CAR Group", "Internet", "Online-Automarktplätze in Australien, USA, Brasilien und Korea."],
      ["COH", "Cochlear", "Medizintechnik", "Weltmarktführer bei Hörimplantaten."],
      ["NXT", "NextDC", "Rechenzentren", "Rechenzentrumsbetreiber, profitiert vom KI-Ausbau."],
      ["SGP", "Stockland", "Immobilien", "Wohnbau und Gewerbeimmobilien."],
      ["MIN", "Mineral Resources", "Bergbau", "Lithium, Eisenerz und Bergbaudienstleistungen; hoch verschuldet."],
      ["PLS", "Pilbara Minerals", "Bergbau", "Großer Lithiumförderer, abhängig vom Lithiumpreis."],
      ["APA", "APA Group", "Infrastruktur", "Gaspipelines und Energieinfrastruktur."],
      ["ALQ", "ALS", "Dienstleistung", "Laboranalysen für Bergbau, Umwelt und Lebensmittel."],
      ["LYC", "Lynas Rare Earths", "Bergbau", "Größter Produzent seltener Erden außerhalb Chinas."],
      ["SEK", "Seek", "Internet", "Führendes Jobportal in Australien und Asien."],
      ["TNE", "Technology One", "Software", "Verwaltungssoftware für Behörden und Universitäten."],
      ["JBH", "JB Hi-Fi", "Einzelhandel", "Elektronik- und Haushaltswarenhändler."],
      ["AMC", "Amcor", "Verpackung", "Verpackungskonzern, seit der Übernahme von Berry Global noch größer."],
      ["TWE", "Treasury Wine Estates", "Getränke", "Weinmarken wie Penfolds."],
    ],
    growth: [
      ["ZIP", "Zip Co", "Fintech", "Ratenkauf („Jetzt kaufen, später zahlen“) in Australien und den USA."],
      ["HUB", "HUB24", "Finanzdienste", "Investmentplattform für Finanzberater mit starkem Mittelzufluss."],
      ["NWL", "Netwealth", "Finanzdienste", "Vermögensverwaltungsplattform für Berater."],
      ["4DX", "4DMedical", "Medizintechnik", "Lungenbildgebung per Software aus Röntgenaufnahmen."],
      ["TLX", "Telix Pharmaceuticals", "Biotech", "Radiopharmazeutika für die Prostatakrebs-Diagnostik."],
      ["MP1", "Megaport", "Cloud", "Netzwerkverbindungen zwischen Rechenzentren und Clouds per Software."],
      ["WEB", "Web Travel Group", "Reisen", "Hotelbuchungsplattform WebBeds für Reisebüros."],
      ["DRO", "DroneShield", "Rüstung", "Systeme zur Drohnenabwehr mit stark gestiegenen Aufträgen."],
      ["CU6", "Clarity Pharmaceuticals", "Biotech", "Radiopharmazeutika auf Kupferbasis."],
      ["NAN", "Nanosonics", "Medizintechnik", "Desinfektionsgeräte für Ultraschallsonden."],
      ["SDR", "SiteMinder", "Software", "Software für Hotelbuchungen und Vertrieb."],
      ["BRN", "BrainChip", "Halbleiter", "Neuromorphe KI-Chips (Akida); kaum Umsatz, sehr spekulativ."],
      ["PNV", "PolyNovo", "Medizintechnik", "Synthetische Hautmatrix für Brandwunden."],
      ["EOS", "Electro Optic Systems", "Rüstung", "Waffenstationen und Laser-Drohnenabwehr."],
      ["NEU", "Neuren Pharmaceuticals", "Biotech", "Medikament gegen das Rett-Syndrom, lizenziert an Acadia."],
      ["AD8", "Audinate", "Technologie", "Audio-Netzwerktechnik Dante für Profi-Audio."],
      ["CAT", "Catapult Sports", "Sporttechnologie", "Wearables und Analysesoftware für den Profisport."],
      ["LOV", "Lovisa", "Einzelhandel", "Günstiger Modeschmuck mit schneller internationaler Expansion."],
      ["PWH", "PWR Holdings", "Industrie", "Kühlsysteme für Motorsport und Luftfahrt."],
      ["LTR", "Liontown Resources", "Bergbau", "Lithiummine Kathleen Valley in Westaustralien."],
    ],
  },
  {
    id: "mx", name: "Mexiko", ex: "Bolsa Mexicana (BMV)", tz: "America/Mexico_City", sess: [[510, 900]], cur: "MXN", c: "MX",
    top: [
      ["WALMEX", "Walmart de México", "Einzelhandel", "Größter Einzelhändler Mexikos und Mittelamerikas (Walmart, Bodega Aurrerá, Sam's Club).", null, ["WALMART DE MEXICO"]],
      ["AMXB", "América Movil", "Telekom", "Größter Mobilfunkkonzern Lateinamerikas (Telcel, Claro), kontrolliert von Carlos Slim.", null, ["AMX"]],
      ["GFNORTEO", "Banorte", "Bank", "Größte mexikanische Bank in einheimischem Besitz.", null, ["GFNORTE"]],
      ["FEMSAUBD", "FEMSA", "Einzelhandel & Getränke", "OXXO-Läden, Beteiligung an Coca-Cola FEMSA und Apotheken.", null, ["FEMSA"]],
      ["GMEXICOB", "Grupo México", "Bergbau & Bahn", "Kupferbergbau (Southern Copper), Eisenbahn und Infrastruktur.", null, ["GMEXICO"]],
      ["CEMEXCPO", "Cemex", "Baustoffe", "Einer der größten Zementhersteller der Welt.", null, ["CEMEX"]],
      ["BIMBOA", "Grupo Bimbo", "Lebensmittel", "Weltgrößte Großbäckerei (Bimbo, Sara Lee, Entenmann's).", null, ["BIMBO"]],
      ["GAPB", "Grupo Aeroportuario del Pacífico", "Flughäfen", "Zwölf Flughäfen in Mexiko und zwei in Jamaika.", null, ["GAP"]],
      ["ASURB", "ASUR", "Flughäfen", "Flughäfen in Cancún, Puerto Rico und Kolumbien.", null, ["ASUR"]],
      ["OMAB", "OMA", "Flughäfen", "Flughäfen im Norden und Zentrum Mexikos, u. a. Monterrey.", null, ["OMA"]],
      ["KOFUBL", "Coca-Cola FEMSA", "Getränke", "Größter Coca-Cola-Abfüller der Welt nach Volumen.", null, ["KOF"]],
      ["AC", "Arca Continental", "Getränke", "Coca-Cola-Abfüller in Mexiko, den USA und Südamerika, dazu Snacks.", null, ["ARCA"]],
      ["GCARSOA1", "Grupo Carso", "Mischkonzern", "Einzelhandel (Sanborns), Industrie und Infrastruktur aus dem Slim-Konzern.", null, ["GCARSO"]],
      ["KIMBERA", "Kimberly-Clark de México", "Konsumgüter", "Hygieneprodukte (Kleenex, Huggies) in Mexiko.", null, ["KIMBER"]],
      ["TLEVISACPO", "Televisa", "Medien", "Kabelnetz izzi und Satelliten-TV; Beteiligung an TelevisaUnivision.", null, ["TLEVISA"]],
      ["ORBIA", "Orbia", "Chemie", "PVC, Rohrsysteme (Wavin), Bewässerung (Netafim) und Fluorchemie."],
      ["ALFAA", "Alfa", "Holding", "Industrieholding mit der Lebensmittelsparte Sigma als Kern.", null, ["ALFA"]],
      ["GRUMAB", "Gruma", "Lebensmittel", "Weltgrößter Hersteller von Maismehl und Tortillas (Mission, Maseca).", null, ["GRUMA"]],
      ["PE&OLES", "Peñoles", "Bergbau", "Über Fresnillo größter Silberproduzent der Welt, dazu Gold und Zink.", null, ["PENOLES"]],
      ["BBAJIOO", "BanBajío", "Bank", "Regionalbank für Unternehmen im Industriegürtel Zentralmexikos.", null, ["BBAJIO"]],
      ["GENTERA", "Gentera", "Finanzen", "Mikrokredite (Compartamos) für Kleinunternehmer."],
      ["LABB", "Genomma Lab", "Konsumgüter", "Rezeptfreie Arzneien und Körperpflege.", null, ["LAB"]],
      ["FUNO11", "Fibra Uno", "Immobilien", "Größter Immobilienfonds Mexikos: Büros, Einkaufszentren und Logistik.", null, ["FUNO"]],
      ["Q", "Quálitas", "Versicherung", "Marktführer bei Kfz-Versicherungen in Mexiko.", null, ["QUALITAS"]],
      ["CHDRAUIB", "Chedraui", "Einzelhandel", "Supermärkte in Mexiko und den USA (Smart & Final).", null, ["CHDRAUI"]],
      ["LIVEPOL", "Liverpool", "Einzelhandel", "Größte Kaufhauskette Mexikos, dazu Suburbia und Einkaufszentren.", null, ["LIVERPOOL"]],
      ["MEGACPO", "Megacable", "Telekom", "Kabelnetz- und Glasfaseranbieter.", null, ["MEGA"]],
      ["PINFRA", "Pinfra", "Infrastruktur", "Mautstraßen und Hafenterminals."],
      ["VESTA", "Vesta", "Immobilien", "Industrieparks für Nearshoring-Fabriken."],
      ["GCC", "GCC", "Baustoffe", "Zementhersteller in Nordmexiko und den USA."],
      ["ALSEA", "Alsea", "Gastronomie", "Betreiber von Starbucks, Domino's und Burger King in Lateinamerika und Spanien."],
      ["RA", "Regional", "Bank", "Banregio, Regionalbank aus Monterrey.", null, ["REGIONAL"]],
      ["CUERVO", "Becle", "Getränke", "Tequila José Cuervo und weitere Spirituosen.", null, ["BECLE"]],
      ["BOLSAA", "Bolsa Mexicana de Valores", "Börse", "Betreiber der mexikanischen Börse.", null, ["BOLSA"]],
      ["GFINBURO", "Grupo Financiero Inbursa", "Bank", "Bank- und Versicherungsgruppe von Carlos Slim.", null, ["GFINBUR"]],
      ["ELEKTRA", "Grupo Elektra", "Einzelhandel & Bank", "Elektronikhandel und Banco Azteca; Streit mit der Steuerbehörde."],
      ["SITES1", "Operadora de Sites Mexicanos", "Telekom-Infrastruktur", "Funkturm-Betreiber aus dem Umfeld von América Movil.", null, ["SITES"]],
      ["FIBRAPL14", "Fibra Prologis", "Immobilien", "Logistikimmobilien von Prologis in Mexiko.", null, ["FIBRAPL"]],
      ["DANHOS13", "Fibra Danhos", "Immobilien", "Premium-Einkaufszentren und Büros in Mexiko-Stadt.", null, ["DANHOS"]],
      ["SORIANAB", "Soriana", "Einzelhandel", "Supermarktkette.", null, ["SORIANA"]],
      ["LACOMERUBC", "La Comer", "Einzelhandel", "Premium-Supermärkte (City Market, Fresko).", null, ["LACOMER"]],
      ["HERDEZ", "Grupo Herdez", "Lebensmittel", "Saucen, Fertiggerichte und Eiscreme-Beteiligungen."],
      ["AGUA", "Rotoplas", "Industrie", "Wassertanks, Rohre und Wasseraufbereitung.", null, ["ROTOPLAS"]],
      ["VOLARA", "Volaris", "Luftfahrt", "Billigfluglinie in Mexiko und den USA.", null, ["VOLAR"]],
      ["TRAXIONA", "Traxión", "Logistik", "Lkw- und Personentransport sowie Logistik.", null, ["TRAXION"]],
      ["SIMECB", "Simec", "Stahl", "Hersteller von Langstahl in Mexiko und den USA.", null, ["SIMEC"]],
      ["AUTLANB", "Autlán", "Bergbau", "Manganerz und Ferrolegierungen.", null, ["AUTLAN"]],
      ["GISSAA", "GIS", "Industrie", "Gussteile für die Autoindustrie und Baustoffe.", null, ["GISSA"]],
      ["NEMAKA", "Nemak", "Autozulieferer", "Aluminiumgussteile für Motoren und Elektroautos.", null, ["NEMAK"]],
      ["ALPEKA", "Alpek", "Chemie", "PET-Kunststoff und Polyester.", null, ["ALPEK"]],
    ],
    growth: [
      ["FMTY14", "Fibra Monterrey", "Immobilien", "Industrie- und Büroimmobilien in Nordmexiko; profitiert von Nearshoring.", null, ["FMTY"]],
      ["FIBRAMQ12", "Fibra Macquarie", "Immobilien", "Industrie- und Handelsimmobilien.", null, ["FIBRAMQ"]],
      ["TERRA13", "Fibra Terrafina", "Immobilien", "Industrieimmobilien im Norden Mexikos.", null, ["TERRA"]],
      ["GMXT", "GMéxico Transportes", "Logistik", "Größtes Eisenbahnnetz Mexikos (Ferromex)."],
      ["HOTEL", "Grupo Hotelero Santa Fe", "Tourismus", "Hotels in Urlaubs- und Geschäftsregionen Mexikos."],
      ["VINTE", "Vinte", "Wohnungsbau", "Nachhaltiger Wohnungsbau für die Mittelschicht."],
      ["CMOCTEZ", "Cementos Moctezuma", "Baustoffe", "Zementhersteller mit hohen Margen."],
      ["LAMOSA", "Lamosa", "Baustoffe", "Fliesen und Baustoffe."],
      ["ARA", "Consorcio ARA", "Wohnungsbau", "Wohnungsbau in ganz Mexiko."],
      ["RLHA", "RLH Properties", "Tourismus", "Luxushotels unter Marken wie Rosewood und Four Seasons.", null, ["RLH"]],
      ["ACTINVRB", "Actinver", "Finanzen", "Vermögensverwaltung und Broker.", null, ["ACTINVR"]],
      ["MFRISCOA", "Minera Frisco", "Bergbau", "Gold-, Silber- und Kupferminen.", null, ["MFRISCO"]],
      ["POSADAA", "Grupo Posadas", "Tourismus", "Größte Hotelkette Mexikos (Fiesta Americana).", null, ["POSADAS"]],
      ["CADUA", "Cadu", "Wohnungsbau", "Wohnungsbau in Quintana Roo.", null, ["CADU"]],
      ["PASA", "Promotora Ambiental", "Umwelt", "Abfallwirtschaft und Recycling."],
      ["CERAMICB", "Internacional de Cerámica", "Baustoffe", "Keramikfliesen.", null, ["CERAMIC"]],
      ["FRAGUAB", "Corporativo Fragua", "Apotheken", "Apothekenkette Farmacias Guadalajara.", null, ["FRAGUA"]],
      ["GPH1", "Grupo Palacio de Hierro", "Einzelhandel", "Luxuskaufhäuser in Mexiko.", null, ["GPH"]],
      ["TMMA", "Grupo TMM", "Logistik", "Maritime Logistik und Häfen.", null, ["TMM"]],
      ["GICSAB", "Grupo GICSA", "Immobilien", "Einkaufszentren und Mischnutzungsprojekte.", null, ["GICSA"]],
    ],
  },
  {
    id: "br", name: "Brasilien", ex: "B3 São Paulo", tz: "America/Sao_Paulo", sess: [[600, 1020]], cur: "BRL", c: "BR",
    top: [
      ["PETR4", "Petrobras", "Öl & Gas", "Staatlich kontrollierter Ölkonzern mit Tiefsee-Förderung (Pré-sal); hohe Dividenden, politisches Risiko.", null, ["PETROBRAS"]],
      ["VALE3", "Vale", "Bergbau", "Einer der größten Eisenerz- und Nickelproduzenten der Welt.", null, ["VALE"]],
      ["ITUB4", "Itaú Unibanco", "Bank", "Größte Privatbank Lateinamerikas und sehr profitabel.", null, ["ITAU"]],
      ["BBDC4", "Bradesco", "Bank", "Große Privatbank und Versicherer, im Umbau nach schwachen Jahren.", null, ["BRADESCO"]],
      ["BBAS3", "Banco do Brasil", "Bank", "Staatlich kontrollierte Bank, stark im Agrarkredit.", null, ["BANCO DO BRASIL"]],
      ["WEGE3", "WEG", "Elektrotechnik", "Elektromotoren, Transformatoren und Automatisierung; globaler Qualitätsführer.", null, ["WEG"]],
      ["ABEV3", "Ambev", "Getränke", "Größter Bierbrauer Lateinamerikas (Brahma, Skol), Teil von AB InBev.", null, ["AMBEV"]],
      ["BPAC11", "BTG Pactual", "Finanzen", "Größte Investmentbank Lateinamerikas.", null, ["BTG"]],
      ["ITSA4", "Itaúsa", "Holding", "Holding mit Anteilen an Itaú Unibanco und Industrieunternehmen.", null, ["ITAUSA"]],
      ["SBSP3", "Sabesp", "Wasserversorger", "Wasser- und Abwasserversorger von São Paulo, 2024 privatisiert.", null, ["SABESP"]],
      ["ELET3", "Eletrobras (Axia Energia)", "Versorger", "Größter Stromerzeuger Brasiliens, vor allem Wasserkraft; 2022 privatisiert.", null, ["AXIA3", "ELETROBRAS"]],
      ["SUZB3", "Suzano", "Zellstoff", "Weltgrößter Hersteller von Eukalyptus-Zellstoff.", null, ["SUZANO"]],
      ["B3SA3", "B3", "Börse", "Betreiber der brasilianischen Börse."],
      ["RDOR3", "Rede D'Or", "Gesundheit", "Größte private Krankenhauskette Brasiliens.", null, ["REDE DOR"]],
      ["EMBR3", "Embraer", "Luftfahrt", "Drittgrößter Flugzeugbauer der Welt: Regionaljets und Militärtransporter KC-390.", null, ["EMBJ3", "EMBRAER"]],
      ["PRIO3", "PRIO", "Öl", "Unabhängiger Ölproduzent mit reifen Feldern und sehr niedrigen Förderkosten."],
      ["RENT3", "Localiza", "Autovermietung", "Größter Autovermieter Lateinamerikas.", null, ["LOCALIZA"]],
      ["EQTL3", "Equatorial", "Versorger", "Stromverteilnetze in Nord- und Nordostbrasilien.", null, ["EQUATORIAL"]],
      ["CMIG4", "Cemig", "Versorger", "Stromversorger im Bundesstaat Minas Gerais.", null, ["CEMIG"]],
      ["VIVT3", "Telefônica Brasil (Vivo)", "Telekom", "Größter Mobilfunkanbieter Brasiliens.", null, ["TELEFONICA BRASIL"]],
      ["TIMS3", "TIM Brasil", "Telekom", "Mobilfunkanbieter, Tochter von Telecom Italia.", null, ["TIM"]],
      ["RADL3", "Raia Drogasil", "Apotheken", "Größte Apothekenkette Brasiliens.", null, ["RAIA"]],
      ["GGBR4", "Gerdau", "Stahl", "Größter Stahlhersteller Brasiliens, auch in den USA aktiv.", null, ["GERDAU"]],
      ["CSAN3", "Cosan", "Holding", "Beteiligungen an Raízen (Ethanol), Rumo (Bahn) und Moove.", null, ["COSAN"]],
      ["UGPA3", "Ultrapar", "Energie", "Tankstellen (Ipiranga) und Flüssiggas (Ultragaz).", null, ["ULTRAPAR"]],
      ["BBSE3", "BB Seguridade", "Versicherung", "Versicherungsgeschäft von Banco do Brasil."],
      ["CPLE6", "Copel", "Versorger", "Stromversorger aus Paraná, 2023 privatisiert.", null, ["CPLE3", "COPEL"]],
      ["ENGI11", "Energisa", "Versorger", "Stromnetze in mehreren Bundesstaaten.", null, ["ENERGISA"]],
      ["KLBN11", "Klabin", "Papier", "Größter Hersteller von Verpackungspapier Brasiliens.", null, ["KLABIN"]],
      ["TOTS3", "TOTVS", "Software", "Größter Anbieter von Unternehmenssoftware (ERP) in Brasilien.", null, ["TOTVS"]],
      ["RAIL3", "Rumo", "Logistik", "Größter Eisenbahnbetreiber Brasiliens für Agrarexporte.", null, ["RUMO"]],
      ["HAPV3", "Hapvida", "Gesundheit", "Krankenversicherer mit eigenen Kliniken.", null, ["HAPVIDA"]],
      ["VBBR3", "Vibra Energia", "Energie", "Größter Kraftstoffhändler Brasiliens (ehemals BR Distribuidora).", null, ["VIBRA"]],
      ["SANB11", "Santander Brasil", "Bank", "Brasilianische Tochter von Banco Santander."],
      ["CXSE3", "Caixa Seguridade", "Versicherung", "Versicherungsgeschäft der Staatsbank Caixa."],
      ["PSSA3", "Porto Seguro", "Versicherung", "Größter Kfz-Versicherer Brasiliens.", null, ["PORTO SEGURO"]],
      ["CPFE3", "CPFL Energia", "Versorger", "Stromversorger, kontrolliert von State Grid of China.", null, ["CPFL"]],
      ["EGIE3", "Engie Brasil", "Versorger", "Größter privater Stromerzeuger Brasiliens.", null, ["ENGIE BRASIL"]],
      ["LREN3", "Lojas Renner", "Mode", "Größte Modekette Brasiliens.", null, ["RENNER"]],
      ["CMIN3", "CSN Mineração", "Bergbau", "Eisenerz-Tochter von CSN."],
      ["MULT3", "Multiplan", "Immobilien", "Premium-Einkaufszentren.", null, ["MULTIPLAN"]],
      ["MBRF3", "MBRF (Marfrig & BRF)", "Lebensmittel", "Fleisch- und Geflügelkonzern nach Fusion von Marfrig und BRF (Sadia, Perdigão).", null, ["BRFS3", "MRFG3"]],
      ["CSNA3", "CSN", "Stahl", "Stahl, Zement und Bergbau.", null, ["SIDERURGICA NACIONAL"]],
      ["ASAI3", "Assaí", "Einzelhandel", "Großmarkt-Kette im Cash-and-Carry-Format.", null, ["ASSAI"]],
      ["HYPE3", "Hypera", "Pharma", "Größter Pharmahersteller Brasiliens (rezeptfreie Mittel und Generika).", null, ["HYPERA"]],
      ["GOAU4", "Metalúrgica Gerdau", "Holding", "Holding von Gerdau."],
      ["TAEE11", "Taesa", "Stromnetze", "Betreiber von Hochspannungsleitungen mit stabilen Dividenden.", null, ["TAESA"]],
      ["ALOS3", "Allos", "Immobilien", "Einkaufszentren nach Fusion von Aliansce und Sonae Sierra.", null, ["ALLOS"]],
      ["SMFT3", "Smart Fit", "Fitness", "Größte Fitnessstudio-Kette Lateinamerikas.", null, ["SMART FIT"]],
      ["NATU3", "Natura", "Kosmetik", "Kosmetik und Direktvertrieb (Natura, Avon).", null, ["NTCO3", "NATURA"]],
    ],
    growth: [
      ["INTB3", "Intelbras", "Technologie", "Sicherheitstechnik, Netzwerke und Solar."],
      ["VAMO3", "Vamos", "Vermietung", "Vermietung von Lkw und Maschinen."],
      ["LWSA3", "Locaweb", "Software", "Hosting und E-Commerce-Software."],
      ["CASH3", "Méliuz", "Fintech", "Cashback-App; hält Bitcoin in der Bilanz."],
      ["MILS3", "Mills", "Vermietung", "Vermietung von Hebebühnen und Baumaschinen."],
      ["POMO4", "Marcopolo", "Fahrzeugbau", "Busaufbauten mit Export in viele Länder."],
      ["FRAS3", "Fras-le", "Autozulieferer", "Bremsbeläge und Autoteile."],
      ["TUPY3", "Tupy", "Industrie", "Gussteile für Motoren und Nutzfahrzeuge."],
      ["ORVR3", "Orizon", "Umwelt", "Abfallwirtschaft und Biogas."],
      ["CURY3", "Cury", "Wohnungsbau", "Wohnungsbau im Förderprogramm „Minha Casa Minha Vida“."],
      ["DIRR3", "Direcional", "Wohnungsbau", "Wohnungsbau für einkommensschwächere Haushalte."],
      ["PLPL3", "Plano & Plano", "Wohnungsbau", "Wohnungsbau in São Paulo."],
      ["VIVA3", "Vivara", "Einzelhandel", "Größte Schmuckkette Brasiliens."],
      ["TGMA3", "Tegma", "Logistik", "Fahrzeuglogistik."],
      ["ARML3", "Armac", "Vermietung", "Vermietung schwerer Maschinen."],
      ["BLAU3", "Blau Farmacêutica", "Pharma", "Biologika und Krankenhausmedikamente."],
      ["MDNE3", "Moura Dubeux", "Wohnungsbau", "Wohnungsbau im Nordosten Brasiliens."],
      ["VULC3", "Vulcabras", "Konsumgüter", "Sportschuhe (Olympikus, Mizuno-Lizenz)."],
      ["POSI3", "Positivo Tecnologia", "Technologie", "Computer, Bildungstechnik und Zahlungsterminals."],
      ["RANI3", "Irani", "Papier", "Verpackungspapier aus Recyclingfasern."],
    ],
  },
];
